spring.application.name=veebipood
# kui tekib port on juba hõivatud error siis:
# server.port = "port number"

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://dpg-d6unkr1r0fns73bqgvc0-a.frankfurt-postgres.render.com/veebipood_database_dl96
spring.datasource.username=veebipood_user
spring.datasource.password=YE8yzyCV5dSmRByUchs2nqnNOOQXe8Km